### ISSUE TITLE
Feature request: add YAML output option

### ISSUE THREAD

**Issue by Houlistonm** [itchyny/gojo#1]
When ever I need a piece of yaml, I fall back to the tools on hand (gojo and gojq) like

`echo -e "---\n$(gojo "A"="B" | gojq --yaml-output -re .)"`

```yaml
---
A: B
```
If gojo were to consume the gojq library, I could type:

`echo -e "---\n$(gojo --yaml-output -r "A"="B")"`

**Comment by itchyny** [comment]
Interesting feature request. Maybe adding an option for YAML output is enough? Considering the existing flags of this tool, how about adding only short flag?
```sh
 $ gojo -y a=1 b=$(gojo c=1)
a: 1
b:
  c: 1
```

**Comment by Houlistonm** [comment]
That would be great.

**Comment by itchyny** [comment]
I finally implemented YAML output option `-y`. It keeps the key order and also supports multi-line string!
```bash
 $ gojo -y a=1 b[]=$(gojo f[]=3 d[][]=2 c=1) c=$'This is\na multi-line\nstring.'
a: 1
b:
  - f:
      - 3
    d:
      - - 2
    c: 1
c: |-
  This is
  a multi-line
  string.
```

**Comment by Houlistonm** [comment]
Fantastic, thanks!
